### PR TITLE
Update doc/index.rst

### PR DESCRIPTION
**Pull request by kaptk2**
Extended installation instructions. My restructured text is really weak so if I need to fix something before this pull will be accepted please let me know.

### CODE REVIEW

**Comment by whiteinge** [comment]
@kaptk2 Thanks for the pull req! The docs really could benefit from expanded installation instructions since it's not obvious how to get started. That said, I don't think the `index.rst` file is the place to put them. Although the `rest_cherrypy` module is currently the only netapi module in salt-api, there could (and will) be others. I think these docs would be more appropriate either in the rest_cherrypy module docs or in a separate installation doc.

**Comment by kaptk2** [comment]
Perhaps a separate quick start page? Just something to get people started
using salt-api. As time goes on the more advanced stuff can be filled it.

**Comment by whiteinge** [comment]
Yeah, good call. A quick start page would be perfect.

**Comment by whiteinge** [comment]
Superseded by #41.

**Pull request closed without merging**
