### PR TITLE
Expose cherrypy metrics

### PR DESCRIPTION
**Pull request by LucasEwalt**
Expose cherrycp cpstats via /stats URI. http://docs.cherrypy.org/en/latest/refman/lib/cpstats.html?highlight=cpstats#module-cherrypy.lib.cpstats

### CODE REVIEW

**Comment by whiteinge** [comment]
Great addition. Thanks! I hadn't played with cpstats before now and that is nice info to see.

If you don't mind, I'd like to modify the return data so it respects the content-negotiation stuffs and returns json/yaml/etc by default. I think we should still be able to make it return HTML if you hit that page in a browser too.

**Comment by LucasEwalt** [comment]
Sure, that'd be cool. The main use case we will use initially is fetching json to feed into our metric collection system. FYI in the current implementation, json is returned via the /stats/data URI. That is how the StatsPage class from cpstats is setup.

HTML when viewing in a browser would be cool too.

**Comment by whiteinge** [comment]
@LucasEwalt changed in daad510. The URL changed to just `/stats` and returns data in the format requested via the "Accept" header.

I need to shuffle things around just a tad for the HTML output so I'll get that added in a second commit.

**Comment by LucasEwalt** [comment]
@whiteinge awesome. I think there are also server stats cherrypy can expose in addition to application stats. You'll notice the server stats section in the return data is currently disabled. I haven't found much documentation yet other than this: https://bitbucket.org/cherrypy/cherrypy/wiki/WhatsNewIn32. 'There's ''also'' new stats code in `wsgiserver`: turn it on by setting `cherrypy.server.httpserver.stats['Enabled']` to `True`'. If I can figure out how to enable i'll send another pull req.

BTW, any idea when v0.8.4 is planned to be cut?

**Comment by whiteinge** [comment]
@LucasEwalt I'd like to secure access to the stats page since it contains sensitive data. I added that in 5b1f6372eab8. Does that work for you?

Also, I'm trying to get 0.8.4 cut this weekend or early next week at the latest. (Sorry, I missed your last question.)

**Pull request merged**
