### PR TITLE
Added required attributes for cmd parser mixins after changes in Salt 0.15.9

### PR DESCRIPTION
**Pull request by slai**
Without these changes, salt-api will not start when installed with Salt 0.15.9 (dies with an error saying _default_logging_logfile_ is not defined).

See Salt commits c3bfde339a and 92da051c00. Also moved the default logging location to /var/log/salt to bring it inline with the rest of the Salt logs.

### CODE REVIEW

**Comment by whiteinge** [comment]
Thanks!

**Comment by s0undt3ch** [comment]
Dam! For salt-api! Sorry @whiteinge...

**Comment by whiteinge** [comment]
I can't stay mad at @s0undt3ch !

**Comment by s0undt3ch** [comment]
heheheeh `s/For/Forgot/`

**Pull request merged**
